language: php

php:
  - 7.0
  - 7.1

before_script:
  - cp .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan jwt:secret
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE forge;'

script:
  - phpunit

services:
  - mysql

notifications:
  email: false
